"""add geolocation fields

Revision ID: 014e47a9fb5c
Revises: 4cc46c944f50
Create Date: 2025-11-22 22:36:58.646224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014e47a9fb5c'
down_revision: Union[str, Sequence[str], None] = '4cc46c944f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_analytics', sa.Column('country', sa.String(), nullable=True))
    op.add_column('scan_analytics', sa.Column('city', sa.String(), nullable=True))
    op.add_column('scan_analytics', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('scan_analytics', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('scan_analytics', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('scan_analytics', sa.Column('isp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_analytics', 'isp')
    op.drop_column('scan_analytics', 'timezone')
    op.drop_column('scan_analytics', 'longitude')
    op.drop_column('scan_analytics', 'latitude')
    op.drop_column('scan_analytics', 'city')
    op.drop_column('scan_analytics', 'country')
    # ### end Alembic commands ###
